type Step = {
  question?: string;
  choices?: Record<string, number>;
  result?: string;
};

export type FlowChartData = Record<number, Step>;

export const flowchartData:FlowChartData = {
    1: {
      question: "You shall not kill. Ever?",
      choices: {
        yes: 2,
        no: 4
      }
    },
    2: {
      question: "Is it ever permitted to kill in self defence?",
      choices: {
        yes: 3,
        no: 4
      }
    },
    3: {
      question: "May a nation-state kill in self defence?",
      choices: {
        yes: 5,
        no: 4
      }
    },
    4: {
      question: "You may be a pacifist, but please continue with other questions which are still relevant to your case.",
      choices: {
        next: 12
      }
    },
    5: {
      question: "May a state, acting in self-defence, kill civilians as the result of a military action?",
      choices: {
        yes: 6,
        no: 12
      }
    },
    6: {
      question: "May a state, acting in self defence, kill civilians through a deliberate policy?",
      choices: {
        yes: 7,
        no: 9
      }
    },
    7: {
      question: "You have accepted the standard by which mass bombing of cities during World War 2 was justified.",
      choices: {
        next: 8
      }

    },
    8: {
      question: "May a state intentionally kill civilians using NW deployed as a deterrent?",
      choices: {
        yes: 24,
        no: 47
      }
    },
    9: {
      question: "Can NW be an effective deterrent if the intended use is limited to ensuring defeat for aggressors (e.g. by targetting of military infrastructure)?",
      choices: {
        yes: 10,
        no: 12
      }
    },
    10: {
      question: "Are you prepared to take an action that inevitably results in destruction of some innocent lives?",
      choices: {
        yes: 11,
        no: 12
      }
    },
    11: {
      question: "You must estimate the loss of life that would result from this action in a practical war situation, including the response of your forces to an escalating conflict. Can you accept responsibility for this?",
      choices: {
        yes: 24,
        no: 12
      }
    },
    12: {
      question: "Is it acceptable for a state merely to possess nuclear weapons as a means of keeping the peace?",
      choices: {
        yes: 13,
        no: 35
      }
    },
    13: {
      question: "Is it acceptable for a state to be willing to use NW if it is so attacked, believing that this therefore is very unlikely to happen",
      choices: {
        yes: 14,
        no: 15
      }
    },
    14: {
     question: "CONDITIONS FOR DETERRENCE The potential aggressor must believe that the capability and the will to retaliate will survive a nuclear attack. He must believe that individual members of the defending forces are sufficiently disciplined that they would inflict an appalling death on millions of innocent people, even after it would serve no useful purpose, deterrence having failed",
     choices:{
      next: 16
     }
    },
    15: {
      question: "Is it acceptable for a state to thus threaten to use NW, while not intending to?",
      choices: {
        yes: 18,
        no: 21
      }
    },
    16: {
      question: "Are these conditions morally acceptable?",
      choices: {
        yes: 17,
        no: 15
      }
    },
    17: {
      question: "Are they attainable in practice?",
      choices: {
        yes: 24,
        no: 44
      }
    },
    18: {
      question: "Could it be done without also deceiving a large proportion of the population?",
      choices: {
        yes: 20,
        no: 19
      }
    },
    19: {
      question: "Is this morally acceptable?",
      choices: {
        yes: 20,
        no: 22
      }
    },
    20: {
      question: "Are you very optimistic, or have you handed over your conscience to your government?",
      choices: {
        next: 24
      }
    },
    21: {
      question: "Is the possession and deployment of NW, such that the perceived threat or the fear generated by uncertainty is an effective deterrent, a morally acceptable means of defence?",
      choices: {
        yes: 24,
        no: 22
      }
    },
    22: {
      question: "Could a nuclear deterrent be an effective defence against non-national groups using NW?",
      choices: {
        yes: 23,
        no: 35
      }
    },
    23: {
      question: "Do you need to re-examine the case for retaining a deterrent in these circumstances?",
      choices: {
        yes: 44,
        no: 35
      }
    },
    24: {
      question: "Are you certain that your state could not become an aggressor during the lifetime of a long-term nuclear defence policy?",
      choices: {
        yes: 25,
        no: 44
      }
    },
    25: {
      question: "You believe that your state has some intrinsic stability or moral superiority that is lacked by potential enemies",
      choices: {
       next: 26
      }
    },
    26: {
      question: "As holders of NW, could you deny other states the right to seek security through NW?",
      choices: {
        yes: 28,
        no: 27
      }
    },
    27: {
      question: "So is it likely that some more will want to do so?",
      choices: {
        yes: 29,
        no: 30
      }
    },
    28: {
      question: "Will this moral censure be likely to prevent them from doing so?",
      choices: {
        yes: 30,
        no: 29
      }
    },
    29: {
      question: "Is there any other long-term effective prevention?",
      choices: {
        yes: 30,
        no: 31
      }
    },
    30: {
      question: `Is escalation of the destructive capability of the nuclear states a most likely consequence of the "balance of terror" ?`,
      choices: {
        yes: 31,
        no: 32
      }
    },
    31: {
      question: "Is it therefore likely that eventually the policy of deterrence will lead to a nuclear war?",
      choices: {
        yes: 44,
        no: 32
      }
    },
    32: {
      question: "Does the risk of nuclear war imply a risk of serious consequences for neighbouring non-combatant states or even for the the rest of humanity?",
      choices: {
        yes: 33,
        no: 34
      }
    },
    33: {
      question: "Have you the right to achieve your own security by endangering the rest of humanity?",
      choices: {
        yes: 34,
        no: 44
      }
    },
    34: {
      question: "In the face of so much real need in the world can you justify securing your defence through vast expenditure on the nuclear deterrent?",
      choices: {
        yes: 45,
        no: 44
      }
    },
    35: {
      question: "You have renounced the principle of the nuclear deterrent as being immoral. You must therefore put your vote and your best efforts of persuasion behind its abolition, particularly where it is deployed on your behalf or in circumstances controlled by your government. However:",
      choices: {
       next: 36
      }
    },
    36: {
      question: "Would the unconditional abandonment of the nuclear deterrent by your country be more likely or less likely to lead to the use of nuclear weapons in the long term?",
      choices: {
         "more likely": 37,
        "less likely": 38
      }
    },
    37: {
      question: "So do you need to adjust your moral standpoint?",
      choices: {
        yes: 44,
        no: 38
      }
    },
    38: {
      question: "Would the abandonment of the nuclear deterrent mean that your country might be subjugated by others with nuclear weapons?",
      choices: {
        yes: 39,
        no: 40
      }
    },
    39: {
      question: "So are you prepared to compromise your moral standpoint?",
      choices: {
        yes: 44,
        no: 40
      }
    },
    40: {
      question: "Would conventional warfare between nation states become more likely without the nuclear deterrent",
      choices: {
        yes: 41,
        no: 42
      }
    },
    41: {
      question: "So do you need to adjust your moral standpoint?",
      choices: {
        yes: 44,
        no: 42
      }
    },
    42: {
      question: "You may support unilateral nuclear disarmament.",
      choices: {
    next: 43
      }
    },
    43: {
      result: "You must now decide what steps are open to you to bring about the abolition of nuclear weapons.",
    },
    44: {
      result: "Your answers so far, indicate that in the long term you cannot support a nuclear defence policy. If nuclear weapons are deployed by your country, you must decide what course you could support in changing the policy, weighing the risks of various routes to disarmament",
   
    },
    45: {
      question: "You have accepted nuclear weapons for your defence, and therefore also their development, maintenance and deployment. To be involved in this process, through military service, a civilian occupation or merely by paying your taxes, would not be inconsistent with the position you have taken. However, you already bear responsibility to the extent that your decisions could allow use of the weapons in the circumstances and conditions that you have accepted in the above questions.",
      choices: {
    next: 46
      }
    },
    46: {
      result: "You should now examine the morality of practical modes of deployment, e.g. a preventive strike capability - is this an inevitable development of a deterrent policy?"
    },
    47: {
      question: "Is it acceptable for a state to be willing to use a NW as a weapon of mass destruction to deter a conventional attack?",
      choices: {
        yes: 24,
        no: 9
      }
    },
  };